[lib]
name = "simplenetlib"
version = "0.1.1"
authors = ["blueburningcoder <f.karg10@gmail.com>"]

[package]
name = "simplenet"
version = "0.1.0"
authors = ["blueburningcoder <f.karg10@gmail.com>"]

[dependencies]
byteorder = "1.1.0"
nalgebra = "0.13.0"
num = "0.1"
rand = "0.3.14"
